# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mov_B0a0YykQbTdRctkjONheQe3ELZHi
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("NBA_2021.csv")

df = df.dropna()

df.head()

df.info()

df.describe()

df["Efficiency_Rating"] = df["PTS"] + df["TRB"] + df["AST"] + df["STL"] + df["BLK"] - df["TOV"]
print(df[df["G"] > 30][["Player", "Efficiency_Rating"]].nlargest(10, "Efficiency_Rating"))

top_scorers_per_team = (
    df[df["G"] > 20]
    .sort_values(["Tm", "PTS"], ascending=[True, False])
    .groupby("Tm")
    .head(1)
    .reset_index(drop=True)
).sort_values("PTS", ascending=False)
print(top_scorers_per_team[["Tm", "Player", "PTS"]])

plt.figure(figsize=(12, 8))
plt.bar(top_scorers_per_team["Player"], top_scorers_per_team["PTS"], color="skyblue")
plt.xlabel("Player")
plt.ylabel("Points (PTS)")
plt.title("Top Scorers Per Team (Minimum 20 Games Played)")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

df["Efficiency_Rating"] = (
    df["PTS"]
    + df["TRB"]
    + df["AST"]
    + df["STL"]
    + df["BLK"]
    - (df["FGA"] - df["FG"])
    - (df["FTA"] - df["FT"])
    - df["TOV"]
)
top_efficiency_players = df[df["G"] > 20][["Player", "Efficiency_Rating"]].nlargest(
    11, "Efficiency_Rating"
)
print(top_efficiency_players)

plt.barh(
    top_efficiency_players["Player"], top_efficiency_players["Efficiency_Rating"], color="salmon"
)
plt.xlabel("Efficiency Rating")
plt.ylabel("Player")
plt.title("Top 10 Players by Efficiency Rating (Minimum 20 Games Played)")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()
